IF OBJECT_ID(N'[dbo].[ERP_NOTIFICACIONES]', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ERP_NOTIFICACIONES] (
        [Notif_Id] INT IDENTITY(1,1) NOT NULL,
        [User_Id] INT NOT NULL,
        [Tipo] NVARCHAR(60) NOT NULL,
        [Titulo] NVARCHAR(200) NOT NULL,
        [Cuerpo] NVARCHAR(MAX) NULL,
        [Leida] BIT NOT NULL CONSTRAINT [DF_ERP_NOTIFICACIONES_Leida] DEFAULT (0),
        [Link] NVARCHAR(300) NULL,
        [FechaCreacion] DATETIME NOT NULL CONSTRAINT [DF_ERP_NOTIFICACIONES_FechaCreacion] DEFAULT (GETDATE()),
        CONSTRAINT [PK_ERP_NOTIFICACIONES] PRIMARY KEY ([Notif_Id])
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ERP_NOTIFICACIONES_USER'
)
BEGIN
    ALTER TABLE [dbo].[ERP_NOTIFICACIONES]
    ADD CONSTRAINT [FK_ERP_NOTIFICACIONES_USER]
        FOREIGN KEY ([User_Id]) REFERENCES [dbo].[ERP_USERS]([User_Id]);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_ERP_NOTIFICACIONES_USER_LEIDA'
      AND object_id = OBJECT_ID(N'[dbo].[ERP_NOTIFICACIONES]')
)
BEGIN
    CREATE INDEX [IX_ERP_NOTIFICACIONES_USER_LEIDA]
        ON [dbo].[ERP_NOTIFICACIONES] ([User_Id], [Leida], [FechaCreacion] DESC);
END
GO
