-- Fase 5B: Trazabilidad de lotes y series
-- Idempotente: seguro de ejecutar múltiples veces

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ERP_LOTES')
CREATE TABLE ERP_LOTES (
    Lote_Id          INT IDENTITY(1,1) PRIMARY KEY,
    Company_Id       INT NOT NULL,
    Producto_Id      INT NOT NULL,
    NumeroLote       NVARCHAR(100) NOT NULL,
    NumeroSerie      NVARCHAR(100) NULL,
    Almacen_Id       INT NULL,
    FechaRecepcion   DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE),
    FechaVencimiento DATE NULL,
    CantidadInicial  DECIMAL(18,4) NOT NULL DEFAULT 0,
    CantidadActual   DECIMAL(18,4) NOT NULL DEFAULT 0,
    Proveedor_Id     INT NULL,
    Notas            NVARCHAR(500) NULL,
    Activo           BIT NOT NULL DEFAULT 1,
    CreatedAt        DATETIME NOT NULL DEFAULT GETDATE()
);

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'ERP_KARDEX' AND COLUMN_NAME = 'Lote_Id'
)
BEGIN
    ALTER TABLE ERP_KARDEX ADD Lote_Id INT NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'ERP_PRODUCTOS' AND COLUMN_NAME = 'ControlLote'
)
BEGIN
    ALTER TABLE ERP_PRODUCTOS ADD ControlLote BIT NOT NULL DEFAULT 0;
END;

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'ERP_PRODUCTOS' AND COLUMN_NAME = 'ControlSerie'
)
BEGIN
    ALTER TABLE ERP_PRODUCTOS ADD ControlSerie BIT NOT NULL DEFAULT 0;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = 'UX_ERP_LOTES_COMPANY_PRODUCTO_LOTE'
)
BEGIN
    CREATE UNIQUE INDEX UX_ERP_LOTES_COMPANY_PRODUCTO_LOTE
    ON ERP_LOTES (Company_Id, Producto_Id, NumeroLote)
    WHERE NumeroSerie IS NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = 'UX_ERP_LOTES_COMPANY_PRODUCTO_SERIE'
)
BEGIN
    CREATE UNIQUE INDEX UX_ERP_LOTES_COMPANY_PRODUCTO_SERIE
    ON ERP_LOTES (Company_Id, Producto_Id, NumeroSerie)
    WHERE NumeroSerie IS NOT NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = 'IX_ERP_LOTES_PRODUCTO_ALMACEN'
)
BEGIN
    CREATE INDEX IX_ERP_LOTES_PRODUCTO_ALMACEN
    ON ERP_LOTES (Company_Id, Producto_Id, Almacen_Id, Activo);
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = 'IX_ERP_KARDEX_LOTE'
)
BEGIN
    CREATE INDEX IX_ERP_KARDEX_LOTE
    ON ERP_KARDEX (Lote_Id);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_ERP_KARDEX_ERP_LOTES'
)
BEGIN
    ALTER TABLE ERP_KARDEX
    ADD CONSTRAINT FK_ERP_KARDEX_ERP_LOTES
    FOREIGN KEY (Lote_Id) REFERENCES ERP_LOTES(Lote_Id);
END;