/*
  Minuta ERP 07-03-26 - Tablas de registro (SQL Server)
  Ejecutar en la misma base donde existen las tablas ERP_* actuales.
*/

/* =========================================================
   1) PRODUCCIÓN - LOGÍSTICA DE OP (embarque, reservado, OT)
   ========================================================= */
IF OBJECT_ID('dbo.ERP_OP_LOGISTICA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_OP_LOGISTICA (
    OP_Logistica_Id INT IDENTITY(1,1) PRIMARY KEY,
    OP_Id INT NOT NULL,
    FechaEmbarque DATETIME NULL,
    CantidadReservada DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_OP_LOGISTICA_CantidadReservada DEFAULT (0),
    OrdenTrabajo NVARCHAR(100) NULL,
    Observaciones NVARCHAR(500) NULL,
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_OP_LOGISTICA_CreatedAt DEFAULT (GETDATE()),
    UpdatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_OP_LOGISTICA_UpdatedAt DEFAULT (GETDATE()),
    UpdatedBy NVARCHAR(100) NULL,
    CONSTRAINT UQ_ERP_OP_LOGISTICA_OP UNIQUE (OP_Id),
    CONSTRAINT FK_ERP_OP_LOGISTICA_OP FOREIGN KEY (OP_Id) REFERENCES dbo.ERP_OP_PRODUCCION(OP_Id),
    CONSTRAINT CK_ERP_OP_LOGISTICA_CantidadReservada CHECK (CantidadReservada >= 0)
  );
END;
GO

/* =========================================================
   2) PRODUCCIÓN - CATÁLOGO DE MÁQUINAS
   ========================================================= */
IF OBJECT_ID('dbo.ERP_PROD_MAQUINA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_PROD_MAQUINA (
    Maquina_Id INT IDENTITY(1,1) PRIMARY KEY,
    Company_Id INT NOT NULL,
    Codigo NVARCHAR(50) NOT NULL,
    Nombre NVARCHAR(150) NOT NULL,
    CapacidadPiezasHora DECIMAL(18,2) NULL,
    Activa BIT NOT NULL CONSTRAINT DF_ERP_PROD_MAQUINA_Activa DEFAULT (1),
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_PROD_MAQUINA_CreatedAt DEFAULT (GETDATE()),
    UpdatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_PROD_MAQUINA_UpdatedAt DEFAULT (GETDATE()),
    CONSTRAINT UQ_ERP_PROD_MAQUINA_Company_Codigo UNIQUE (Company_Id, Codigo),
    CONSTRAINT FK_ERP_PROD_MAQUINA_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id)
  );
END;
GO

/* =========================================================
   3) PRODUCCIÓN - PLANEACIÓN POR MÁQUINA Y PRIORIDAD
   ========================================================= */
IF OBJECT_ID('dbo.ERP_OP_PLAN_MAQUINA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_OP_PLAN_MAQUINA (
    OP_PlanMaquina_Id INT IDENTITY(1,1) PRIMARY KEY,
    OP_Id INT NOT NULL,
    Maquina_Id INT NOT NULL,
    Prioridad INT NOT NULL,
    Secuencia INT NULL,
    FechaInicioPlan DATETIME NULL,
    FechaFinPlan DATETIME NULL,
    Estatus NVARCHAR(30) NOT NULL CONSTRAINT DF_ERP_OP_PLAN_MAQUINA_Estatus DEFAULT ('PENDIENTE'),
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_OP_PLAN_MAQUINA_CreatedAt DEFAULT (GETDATE()),
    UpdatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_OP_PLAN_MAQUINA_UpdatedAt DEFAULT (GETDATE()),
    CONSTRAINT UQ_ERP_OP_PLAN_MAQUINA_OP UNIQUE (OP_Id),
    CONSTRAINT FK_ERP_OP_PLAN_MAQUINA_OP FOREIGN KEY (OP_Id) REFERENCES dbo.ERP_OP_PRODUCCION(OP_Id),
    CONSTRAINT FK_ERP_OP_PLAN_MAQUINA_MAQUINA FOREIGN KEY (Maquina_Id) REFERENCES dbo.ERP_PROD_MAQUINA(Maquina_Id),
    CONSTRAINT CK_ERP_OP_PLAN_MAQUINA_Prioridad CHECK (Prioridad > 0)
  );

  CREATE INDEX IX_ERP_OP_PLAN_MAQUINA_Maquina_Prioridad
    ON dbo.ERP_OP_PLAN_MAQUINA (Maquina_Id, Prioridad, Secuencia);
END;
GO

/* =========================================================
   4) PRODUCCIÓN - REGISTRO DE PIEZAS FABRICADAS (REANUDACIÓN)
   ========================================================= */
IF OBJECT_ID('dbo.ERP_OP_AVANCE_PIEZAS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_OP_AVANCE_PIEZAS (
    OP_Avance_Id INT IDENTITY(1,1) PRIMARY KEY,
    OP_Id INT NOT NULL,
    FechaRegistro DATETIME NOT NULL CONSTRAINT DF_ERP_OP_AVANCE_PIEZAS_FechaRegistro DEFAULT (GETDATE()),
    PiezasBuenas DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_OP_AVANCE_PIEZAS_Buenas DEFAULT (0),
    PiezasMerma DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_OP_AVANCE_PIEZAS_Merma DEFAULT (0),
    EnProceso DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_OP_AVANCE_PIEZAS_EnProceso DEFAULT (0),
    EsCierreParcial BIT NOT NULL CONSTRAINT DF_ERP_OP_AVANCE_PIEZAS_CierreParcial DEFAULT (0),
    Comentarios NVARCHAR(500) NULL,
    RegistradoPor NVARCHAR(100) NULL,
    CONSTRAINT FK_ERP_OP_AVANCE_PIEZAS_OP FOREIGN KEY (OP_Id) REFERENCES dbo.ERP_OP_PRODUCCION(OP_Id),
    CONSTRAINT CK_ERP_OP_AVANCE_PIEZAS_NoNegativos CHECK (
      PiezasBuenas >= 0 AND PiezasMerma >= 0 AND EnProceso >= 0
    )
  );

  CREATE INDEX IX_ERP_OP_AVANCE_PIEZAS_OP_Fecha
    ON dbo.ERP_OP_AVANCE_PIEZAS (OP_Id, FechaRegistro DESC);
END;
GO

/* =========================================================
   5) CALIDAD - ALERTAS Y SOLICITUD AUTOMÁTICA DE OP
   ========================================================= */
IF OBJECT_ID('dbo.ERP_CALIDAD_ALERTA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_CALIDAD_ALERTA (
    CalidadAlerta_Id INT IDENTITY(1,1) PRIMARY KEY,
    Company_Id INT NOT NULL,
    Producto_Id INT NOT NULL,
    Motivo NVARCHAR(200) NOT NULL,
    Severidad NVARCHAR(20) NOT NULL CONSTRAINT DF_ERP_CALIDAD_ALERTA_Severidad DEFAULT ('MEDIA'),
    CantidadSugerida DECIMAL(18,2) NULL,
    RequiereOP BIT NOT NULL CONSTRAINT DF_ERP_CALIDAD_ALERTA_RequiereOP DEFAULT (1),
    OP_Generada_Id INT NULL,
    Estatus NVARCHAR(20) NOT NULL CONSTRAINT DF_ERP_CALIDAD_ALERTA_Estatus DEFAULT ('ABIERTA'),
    FechaAlerta DATETIME NOT NULL CONSTRAINT DF_ERP_CALIDAD_ALERTA_FechaAlerta DEFAULT (GETDATE()),
    FechaCierre DATETIME NULL,
    Observaciones NVARCHAR(1000) NULL,
    CreatedBy NVARCHAR(100) NULL,
    CONSTRAINT FK_ERP_CALIDAD_ALERTA_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id),
    CONSTRAINT FK_ERP_CALIDAD_ALERTA_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT FK_ERP_CALIDAD_ALERTA_OP FOREIGN KEY (OP_Generada_Id) REFERENCES dbo.ERP_OP_PRODUCCION(OP_Id),
    CONSTRAINT CK_ERP_CALIDAD_ALERTA_Severidad CHECK (Severidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    CONSTRAINT CK_ERP_CALIDAD_ALERTA_Estatus CHECK (Estatus IN ('ABIERTA', 'ATENDIDA', 'CERRADA'))
  );
END;
GO

/* =========================================================
   6) ALMACÉN - CONSOLIDADO DE INVENTARIO POR ESTADO
      (total almacén, en máquina, entregada a producción, en proceso)
   ========================================================= */
IF OBJECT_ID('dbo.ERP_INVENTARIO_ESTADO_PRODUCTO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_INVENTARIO_ESTADO_PRODUCTO (
    InventarioEstado_Id INT IDENTITY(1,1) PRIMARY KEY,
    Company_Id INT NOT NULL,
    Producto_Id INT NOT NULL,
    Almacen_Id INT NULL,
    CantidadAlmacen DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_INV_EST_Almacen DEFAULT (0),
    CantidadEnMaquina DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_INV_EST_Maquina DEFAULT (0),
    CantidadEntregadaProduccion DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_INV_EST_Entregada DEFAULT (0),
    CantidadEnProceso DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_INV_EST_Proceso DEFAULT (0),
    FechaCorte DATETIME NOT NULL CONSTRAINT DF_ERP_INV_EST_FechaCorte DEFAULT (GETDATE()),
    CONSTRAINT FK_ERP_INV_EST_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id),
    CONSTRAINT FK_ERP_INV_EST_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT FK_ERP_INV_EST_ALMACEN FOREIGN KEY (Almacen_Id) REFERENCES dbo.ERP_ALMACENES(Almacen_Id),
    CONSTRAINT CK_ERP_INV_EST_NoNegativos CHECK (
      CantidadAlmacen >= 0 AND CantidadEnMaquina >= 0 AND
      CantidadEntregadaProduccion >= 0 AND CantidadEnProceso >= 0
    )
  );

  CREATE INDEX IX_ERP_INVENTARIO_ESTADO_PRODUCTO_Company_Producto
    ON dbo.ERP_INVENTARIO_ESTADO_PRODUCTO (Company_Id, Producto_Id, FechaCorte DESC);
END;
GO

/* =========================================================
   7) COMPRAS - ORDEN DE COMPRA (CABECERA)
   ========================================================= */
IF OBJECT_ID('dbo.ERP_COMPRA_ORDEN', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_COMPRA_ORDEN (
    OC_Id INT IDENTITY(1,1) PRIMARY KEY,
    NumeroOC NVARCHAR(50) NOT NULL,
    Company_Id INT NOT NULL,
    Proveedor_Id INT NOT NULL,
    FechaOC DATETIME NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_FechaOC DEFAULT (GETDATE()),
    FechaRequerida DATETIME NULL,
    Moneda NVARCHAR(3) NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_Moneda DEFAULT ('MXN'),
    Subtotal DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_Subtotal DEFAULT (0),
    IVA DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_IVA DEFAULT (0),
    Total DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_Total DEFAULT (0),
    Estatus NVARCHAR(30) NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_Estatus DEFAULT ('BORRADOR'),
    RequiereDobleAutorizacion BIT NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_DobleAuth DEFAULT (1),
    FacturaReferencia NVARCHAR(100) NULL,
    FacturaArchivoUrl NVARCHAR(500) NULL,
    PDFUrl NVARCHAR(500) NULL,
    Observaciones NVARCHAR(1000) NULL,
    CreatedBy NVARCHAR(100) NULL,
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_CreatedAt DEFAULT (GETDATE()),
    UpdatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_UpdatedAt DEFAULT (GETDATE()),
    CONSTRAINT UQ_ERP_COMPRA_ORDEN_NumeroOC UNIQUE (NumeroOC),
    CONSTRAINT FK_ERP_COMPRA_ORDEN_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id),
    CONSTRAINT CK_ERP_COMPRA_ORDEN_Estatus CHECK (
      Estatus IN ('BORRADOR', 'PENDIENTE_AUTORIZACION', 'AUTORIZADA', 'RECHAZADA', 'COMPRADA', 'CANCELADA')
    )
  );
END;
GO

/* =========================================================
   8) COMPRAS - ORDEN DE COMPRA (DETALLE)
   ========================================================= */
IF OBJECT_ID('dbo.ERP_COMPRA_ORDEN_DETALLE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_COMPRA_ORDEN_DETALLE (
    OC_Detalle_Id INT IDENTITY(1,1) PRIMARY KEY,
    OC_Id INT NOT NULL,
    Producto_Id INT NULL,
    MateriaPrima_Id INT NULL,
    Descripcion NVARCHAR(300) NOT NULL,
    Cantidad DECIMAL(18,4) NOT NULL,
    PrecioCompra DECIMAL(18,6) NOT NULL,
    Subtotal DECIMAL(18,2) NOT NULL,
    IVA DECIMAL(18,2) NOT NULL CONSTRAINT DF_ERP_COMPRA_ORDEN_DETALLE_IVA DEFAULT (0),
    Total DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_ERP_COMPRA_ORDEN_DETALLE_OC FOREIGN KEY (OC_Id) REFERENCES dbo.ERP_COMPRA_ORDEN(OC_Id),
    CONSTRAINT FK_ERP_COMPRA_ORDEN_DETALLE_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT FK_ERP_COMPRA_ORDEN_DETALLE_MP FOREIGN KEY (MateriaPrima_Id) REFERENCES dbo.ERP_MATERIA_PRIMA(MateriaPrima_Id),
    CONSTRAINT CK_ERP_COMPRA_ORDEN_DETALLE_Origen CHECK (
      (CASE WHEN Producto_Id IS NULL THEN 0 ELSE 1 END) +
      (CASE WHEN MateriaPrima_Id IS NULL THEN 0 ELSE 1 END) = 1
    ),
    CONSTRAINT CK_ERP_COMPRA_ORDEN_DETALLE_Pos CHECK (Cantidad > 0 AND PrecioCompra >= 0)
  );

  CREATE INDEX IX_ERP_COMPRA_ORDEN_DETALLE_OC
    ON dbo.ERP_COMPRA_ORDEN_DETALLE (OC_Id);
END;
GO

/* =========================================================
   9) COMPRAS - AUTORIZACIONES (DOBLE AUTORIZACIÓN)
   ========================================================= */
IF OBJECT_ID('dbo.ERP_COMPRA_AUTORIZACION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_COMPRA_AUTORIZACION (
    OC_Autorizacion_Id INT IDENTITY(1,1) PRIMARY KEY,
    OC_Id INT NOT NULL,
    Nivel INT NOT NULL,
    User_Id INT NULL,
    Aprobado BIT NOT NULL,
    FechaDecision DATETIME NOT NULL CONSTRAINT DF_ERP_COMPRA_AUTORIZACION_Fecha DEFAULT (GETDATE()),
    Comentarios NVARCHAR(500) NULL,
    CONSTRAINT FK_ERP_COMPRA_AUTORIZACION_OC FOREIGN KEY (OC_Id) REFERENCES dbo.ERP_COMPRA_ORDEN(OC_Id),
    CONSTRAINT FK_ERP_COMPRA_AUTORIZACION_USER FOREIGN KEY (User_Id) REFERENCES dbo.ERP_USERS(User_Id),
    CONSTRAINT CK_ERP_COMPRA_AUTORIZACION_Nivel CHECK (Nivel IN (1,2)),
    CONSTRAINT UQ_ERP_COMPRA_AUTORIZACION_OC_Nivel UNIQUE (OC_Id, Nivel)
  );
END;
GO

/* =========================================================
   10) COSTOS - COSTEO MENSUAL Y MERMAS
   ========================================================= */
IF OBJECT_ID('dbo.ERP_COSTEO_MENSUAL', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_COSTEO_MENSUAL (
    CosteoMensual_Id INT IDENTITY(1,1) PRIMARY KEY,
    Company_Id INT NOT NULL,
    Anio INT NOT NULL,
    Mes INT NOT NULL,
    Producto_Id INT NOT NULL,
    CostoMaterial DECIMAL(18,4) NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_CostoMaterial DEFAULT (0),
    CostoOperacion DECIMAL(18,4) NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_CostoOperacion DEFAULT (0),
    FactorDesperdicio DECIMAL(18,6) NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_FactorDesperdicio DEFAULT (0),
    FactorProductividad DECIMAL(18,6) NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_FactorProductividad DEFAULT (1),
    MermaPctReal DECIMAL(18,6) NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_MermaPctReal DEFAULT (0),
    CostoUnitarioFinal DECIMAL(18,4) NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_CostoFinal DEFAULT (0),
    Notas NVARCHAR(500) NULL,
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_COSTEO_MENSUAL_CreatedAt DEFAULT (GETDATE()),
    CreatedBy NVARCHAR(100) NULL,
    CONSTRAINT FK_ERP_COSTEO_MENSUAL_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id),
    CONSTRAINT FK_ERP_COSTEO_MENSUAL_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT UQ_ERP_COSTEO_MENSUAL_Periodo UNIQUE (Company_Id, Anio, Mes, Producto_Id),
    CONSTRAINT CK_ERP_COSTEO_MENSUAL_Mes CHECK (Mes BETWEEN 1 AND 12),
    CONSTRAINT CK_ERP_COSTEO_MENSUAL_Anio CHECK (Anio BETWEEN 2000 AND 2100)
  );
END;
GO

/* =========================================================
   11) INVENTARIO - CONFIGURACIÓN DE ALMACÉN POR PRODUCTO/EMPRESA
   ========================================================= */
IF OBJECT_ID('dbo.ERP_PRODUCTO_ALMACEN_CONFIG', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_PRODUCTO_ALMACEN_CONFIG (
    ProductoAlmacenConfig_Id INT IDENTITY(1,1) PRIMARY KEY,
    Producto_Id INT NOT NULL,
    Company_Id INT NOT NULL,
    Almacen_Id INT NULL,
    ClasificacionInventario NVARCHAR(30) NOT NULL CONSTRAINT DF_ERP_PRODUCTO_ALMACEN_CONFIG_Clasificacion DEFAULT ('PRODUCTO_TERMINADO'),
    Activo BIT NOT NULL CONSTRAINT DF_ERP_PRODUCTO_ALMACEN_CONFIG_Activo DEFAULT (1),
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_PRODUCTO_ALMACEN_CONFIG_CreatedAt DEFAULT (GETDATE()),
    UpdatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_PRODUCTO_ALMACEN_CONFIG_UpdatedAt DEFAULT (GETDATE()),
    UpdatedBy NVARCHAR(100) NULL,
    CONSTRAINT UQ_ERP_PRODUCTO_ALMACEN_CONFIG UNIQUE (Producto_Id, Company_Id),
    CONSTRAINT FK_ERP_PRODUCTO_ALMACEN_CONFIG_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT FK_ERP_PRODUCTO_ALMACEN_CONFIG_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id),
    CONSTRAINT FK_ERP_PRODUCTO_ALMACEN_CONFIG_ALMACEN FOREIGN KEY (Almacen_Id) REFERENCES dbo.ERP_ALMACENES(Almacen_Id),
    CONSTRAINT CK_ERP_PRODUCTO_ALMACEN_CONFIG_Clasificacion CHECK (
      ClasificacionInventario IN ('MATERIA_PRIMA', 'PRODUCTO_TERMINADO', 'PRODUCTO_REVENTA')
    )
  );

  CREATE INDEX IX_ERP_PRODUCTO_ALMACEN_CONFIG_Company_Almacen
    ON dbo.ERP_PRODUCTO_ALMACEN_CONFIG (Company_Id, Almacen_Id, Producto_Id);
END;
GO

/* =========================================================
   12) INVENTARIO - RECEPCIÓN DE PRODUCTO TERMINADO DESDE PRODUCCIÓN
   ========================================================= */
IF OBJECT_ID('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO (
    RecepcionPT_Id INT IDENTITY(1,1) PRIMARY KEY,
    OP_Id INT NOT NULL,
    Producto_Id INT NOT NULL,
    Company_Id INT NOT NULL,
    Almacen_Id INT NULL,
    CantidadRecibida DECIMAL(18,2) NOT NULL,
    ClasificacionInventario NVARCHAR(30) NOT NULL CONSTRAINT DF_ERP_RECEPCION_PT_Clasificacion DEFAULT ('PRODUCTO_TERMINADO'),
    Estatus NVARCHAR(20) NOT NULL CONSTRAINT DF_ERP_RECEPCION_PT_Estatus DEFAULT ('RECIBIDA'),
    Referencia NVARCHAR(100) NOT NULL,
    Observaciones NVARCHAR(1000) NULL,
    MotivoCancelacion NVARCHAR(1000) NULL,
    FechaCancelacion DATETIME NULL,
    CanceladoBy NVARCHAR(100) NULL,
    CreatedAt DATETIME NOT NULL CONSTRAINT DF_ERP_RECEPCION_PT_CreatedAt DEFAULT (GETDATE()),
    CreatedBy NVARCHAR(100) NULL,
    CONSTRAINT UQ_ERP_RECEPCION_PT_OP UNIQUE (OP_Id),
    CONSTRAINT FK_ERP_RECEPCION_PT_OP FOREIGN KEY (OP_Id) REFERENCES dbo.ERP_OP_PRODUCCION(OP_Id),
    CONSTRAINT FK_ERP_RECEPCION_PT_PRODUCTO FOREIGN KEY (Producto_Id) REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT FK_ERP_RECEPCION_PT_COMPANY FOREIGN KEY (Company_Id) REFERENCES dbo.ERP_COMPANY(Company_Id),
    CONSTRAINT FK_ERP_RECEPCION_PT_ALMACEN FOREIGN KEY (Almacen_Id) REFERENCES dbo.ERP_ALMACENES(Almacen_Id),
    CONSTRAINT CK_ERP_RECEPCION_PT_Cantidad CHECK (
      (Estatus = 'RECIBIDA' AND CantidadRecibida > 0) OR
      (Estatus = 'CANCELADA' AND CantidadRecibida = 0)
    ),
    CONSTRAINT CK_ERP_RECEPCION_PT_Estatus CHECK (Estatus IN ('RECIBIDA', 'CANCELADA')),
    CONSTRAINT CK_ERP_RECEPCION_PT_Clasificacion CHECK (
      ClasificacionInventario IN ('MATERIA_PRIMA', 'PRODUCTO_TERMINADO', 'PRODUCTO_REVENTA')
    )
  );

  CREATE INDEX IX_ERP_RECEPCION_PT_Company_Fecha
    ON dbo.ERP_RECEPCION_PRODUCTO_TERMINADO (Company_Id, CreatedAt DESC);
END;
GO

IF COL_LENGTH('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO', 'Estatus') IS NULL
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO
    ADD Estatus NVARCHAR(20) NOT NULL CONSTRAINT DF_ERP_RECEPCION_PT_Estatus DEFAULT ('RECIBIDA');
END;
GO

IF COL_LENGTH('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO', 'MotivoCancelacion') IS NULL
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO
    ADD MotivoCancelacion NVARCHAR(1000) NULL;
END;
GO

IF COL_LENGTH('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO', 'FechaCancelacion') IS NULL
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO
    ADD FechaCancelacion DATETIME NULL;
END;
GO

IF COL_LENGTH('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO', 'CanceladoBy') IS NULL
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO
    ADD CanceladoBy NVARCHAR(100) NULL;
END;
GO

IF EXISTS (
  SELECT 1
  FROM sys.columns
  WHERE object_id = OBJECT_ID('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO')
    AND name = 'Almacen_Id'
    AND is_nullable = 0
)
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO ALTER COLUMN Almacen_Id INT NULL;
END;
GO

IF EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ERP_RECEPCION_PT_Cantidad'
    AND parent_object_id = OBJECT_ID('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO')
)
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO DROP CONSTRAINT CK_ERP_RECEPCION_PT_Cantidad;
END;
GO

ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO
  ADD CONSTRAINT CK_ERP_RECEPCION_PT_Cantidad CHECK (
    (Estatus = 'RECIBIDA' AND CantidadRecibida > 0) OR
    (Estatus = 'CANCELADA' AND CantidadRecibida = 0)
  );
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_ERP_RECEPCION_PT_Estatus'
    AND parent_object_id = OBJECT_ID('dbo.ERP_RECEPCION_PRODUCTO_TERMINADO')
)
BEGIN
  ALTER TABLE dbo.ERP_RECEPCION_PRODUCTO_TERMINADO
    ADD CONSTRAINT CK_ERP_RECEPCION_PT_Estatus CHECK (Estatus IN ('RECIBIDA', 'CANCELADA'));
END;
GO

IF COL_LENGTH('dbo.ERP_COMPRA_ORDEN', 'FacturaArchivoUrl') IS NULL
BEGIN
  ALTER TABLE dbo.ERP_COMPRA_ORDEN
    ADD FacturaArchivoUrl NVARCHAR(500) NULL;
END;
GO

/* =========================================================
   13) COMPRAS - STOCK DE MATERIA PRIMA
       Equivalente a ERP_STOCK pero para materias primas.
       Se actualiza al recibir una OC con líneas de MP.
   ========================================================= */
IF OBJECT_ID('dbo.ERP_STOCK_MP', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_STOCK_MP (
    StockMP_Id     INT IDENTITY(1,1) PRIMARY KEY,
    MateriaPrima_Id INT NOT NULL,
    Almacen_Id      INT NOT NULL,
    Cantidad        DECIMAL(18,4) NOT NULL CONSTRAINT DF_ERP_STOCK_MP_Cantidad DEFAULT (0),
    Stock_Minimo    DECIMAL(18,4) NOT NULL CONSTRAINT DF_ERP_STOCK_MP_StockMin DEFAULT (0),
    CONSTRAINT UQ_ERP_STOCK_MP_MP_Almacen UNIQUE (MateriaPrima_Id, Almacen_Id),
    CONSTRAINT FK_ERP_STOCK_MP_MP      FOREIGN KEY (MateriaPrima_Id) REFERENCES dbo.ERP_MATERIA_PRIMA(MateriaPrima_Id),
    CONSTRAINT FK_ERP_STOCK_MP_ALMACEN FOREIGN KEY (Almacen_Id)      REFERENCES dbo.ERP_ALMACENES(Almacen_Id),
    CONSTRAINT CK_ERP_STOCK_MP_Cantidad CHECK (Cantidad >= 0)
  );

  CREATE INDEX IX_ERP_STOCK_MP_MP ON dbo.ERP_STOCK_MP (MateriaPrima_Id);
END;
GO

/* =========================================================
   14) COMPRAS - RECEPCIÓN DE MERCANCÍA
       Registra cada recepción vinculada a una OC,
       con las cantidades exactas recibidas por línea.
   ========================================================= */
IF OBJECT_ID('dbo.ERP_COMPRA_RECEPCION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_COMPRA_RECEPCION (
    Recepcion_Id   INT IDENTITY(1,1) PRIMARY KEY,
    OC_Id          INT NOT NULL,
    FechaRecepcion DATETIME NOT NULL CONSTRAINT DF_ERP_COMPRA_RECEPCION_Fecha DEFAULT (GETDATE()),
    Almacen_Id     INT NOT NULL,
    Observaciones  NVARCHAR(500) NULL,
    RecibidoPor    NVARCHAR(100) NULL,
    CreatedAt      DATETIME NOT NULL CONSTRAINT DF_ERP_COMPRA_RECEPCION_CreatedAt DEFAULT (GETDATE()),
    CONSTRAINT FK_ERP_COMPRA_RECEPCION_OC      FOREIGN KEY (OC_Id)      REFERENCES dbo.ERP_COMPRA_ORDEN(OC_Id),
    CONSTRAINT FK_ERP_COMPRA_RECEPCION_ALMACEN FOREIGN KEY (Almacen_Id) REFERENCES dbo.ERP_ALMACENES(Almacen_Id)
  );
END;
GO

IF OBJECT_ID('dbo.ERP_COMPRA_RECEPCION_DETALLE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ERP_COMPRA_RECEPCION_DETALLE (
    RecepcionDetalle_Id INT IDENTITY(1,1) PRIMARY KEY,
    Recepcion_Id        INT NOT NULL,
    OC_Detalle_Id       INT NOT NULL,
    Producto_Id         INT NULL,
    MateriaPrima_Id     INT NULL,
    Descripcion         NVARCHAR(300) NOT NULL,
    CantidadOrdenada    DECIMAL(18,4) NOT NULL,
    CantidadRecibida    DECIMAL(18,4) NOT NULL,
    PrecioCompra        DECIMAL(18,6) NOT NULL,
    CONSTRAINT FK_ERP_COMPRA_REC_DET_REC      FOREIGN KEY (Recepcion_Id)  REFERENCES dbo.ERP_COMPRA_RECEPCION(Recepcion_Id),
    CONSTRAINT FK_ERP_COMPRA_REC_DET_OCDET    FOREIGN KEY (OC_Detalle_Id) REFERENCES dbo.ERP_COMPRA_ORDEN_DETALLE(OC_Detalle_Id),
    CONSTRAINT FK_ERP_COMPRA_REC_DET_PRODUCTO FOREIGN KEY (Producto_Id)   REFERENCES dbo.ERP_PRODUCTOS(Producto_Id),
    CONSTRAINT FK_ERP_COMPRA_REC_DET_MP       FOREIGN KEY (MateriaPrima_Id) REFERENCES dbo.ERP_MATERIA_PRIMA(MateriaPrima_Id),
    CONSTRAINT CK_ERP_COMPRA_REC_DET_Cant     CHECK (CantidadRecibida >= 0)
  );

  CREATE INDEX IX_ERP_COMPRA_REC_DET_Recepcion ON dbo.ERP_COMPRA_RECEPCION_DETALLE (Recepcion_Id);
END;
GO

PRINT 'Script de tablas de registro ejecutado correctamente.';
GO
